language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.3
    - 7.4
    - 8.0snapshot

jobs:
    include:
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
    - ./vendor/bin/phpunit
